---
kind: pipeline
type: docker
name: practice-drone

clone:
  depath: 1

steps:
  - name: build_image_when_push
    image: plugins/ansible
    volumes:
      - name: dockerdaemon
        path: /var/run/docker.sock
    commands:
      - apk update; apk add bash openrc libxml2-utils docker
      - docker run hello-world

volumes:
  - name: dockerdaemon
    host:
      path: /var/run/docker.sock