---
kind: pipeline
type: docker
name: practice-drone

clone:
  depath: 1

steps:
  - name: print drone env
    image: bash
    commands:
      - echo env
      - echo "Tag:${DRONE_TAG}"
      - echo "Branch:${DRONE_BRANCH}"
      - exit 0
