---
kind: pipeline
type: docker
name: practice-drone

clone:
  depath: 1

steps:
  - name: docker-builder
    image: plugins/docker
    settings:
      repo: ajdfajdfl/practice-drone
      tags: latest
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pwd
