---
kind: pipeline
type: docker
name: practice-drone

clone:
  depath: 1

steps:
  - name: print drone env
    image: bash
    commands:
      - echo "${DRONE_BUILD_STATUS}"
      - echo "$DRONE_BUILD_STATUS"
      - echo ${DRONE_BUILD_STATUS}
      - echo $DRONE_BUILD_STATUS
      - echo "DRONE_BUILD_STATUS:$DRONE_BUILD_STATUS"
      - echo "DRONE_BUILD_STATUS:${DRONE_BUILD_STATUS}"
      - exit 0
