---
kind: pipeline
type: docker
name: practice-drone

clone:
  depath: 1

steps:
  - name: build_image_when_push
    image: plugins/ansible
    commands:
      - apk update; apk add bash libxml2-utils docker
