---
kind: pipeline
type: docker
name: practice-drone

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/ajdfajdfl2003/practice-drone.git .
      - git checkout $DRONE_COMMIT

  - name: I Want a Tag
    image: bash
    commands:
      - echo "Tag:${DRONE_TAG}"
    depends_on:
      - clone

  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: test-drone
    depends_on:
      - I Want a Tag

trigger:
  event:
    - tag