---
kind: pipeline
type: docker
name: practice-drone

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - git clone https://github.com/ajdfajdfl2003/practice-drone.git .
      - git checkout $DRONE_COMMIT

  - name: I Want a Tag
    image: bash
    commands:
      - echo "Tag:${DRONE_TAG}"
      - exit 0
    depends_on:
      - clone

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: test-drone
      username: practice-drone
      template: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
    depends_on:
      - I Want a Tag
    status:
      - success
      - failure

trigger:
  event:
    - tag